#!/usr/bin/python3
"""Which WebUI this is, and where to read about it."""
from __future__ import annotations

import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
# Where the version tags are published: autonomy is pushed to the fork.
REPO_URL = "https://github.com/f1adang/brushograph"
# Where a G-code file points anyone who finds it. The host is brušograf, spelled
# in punycode: GRBL and FluidNC take any byte above 127 as a realtime command
# (a feed override, a jog cancel), and a sender streams comments along with
# everything else, so the note stays plain ASCII.
SITE_URL = "http://xn--bruograf-7wb.ignore.net/"


def _version() -> str | None:
    """The newest version tag reachable from the checked-out commit.

    Every feature merged into autonomy is tagged vMAJOR.MINOR, so the tag is
    the version and there is no file to keep in step with it. Read once at
    start: the code a running server executes does not change under it. None
    when there is no git or no tag, and the header then says nothing.
    """
    try:
        out = subprocess.run(
            ["git", "describe", "--tags", "--abbrev=0", "--match", "v[0-9]*"],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=5,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0:
        return None
    return out.stdout.strip() or None


VERSION = _version()


def gcode_note() -> str:
    """The comment line every generated G-code file carries."""
    return f"; Generated by Brushograph WebUI {VERSION or '(unversioned)'}: {SITE_URL}"
